In [2]:
import numpy as np

In [15]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
import time
import sys

In [9]:
l=range(1000)
print(sys.getsizeof(1)*len(l))

14000


In [14]:
a=np.arange(1000)
print(a.size*a.itemsize)

4000


In [ ]:
size=1000000000
l1=range(size)
l2=range(size)

In [ ]:
a1=np.arange(size)
a2=np.arange(size)

In [19]:
%%timeit
result=[(x+y) for x,y in zip(l1,l2)]

3.04 s ± 262 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
%%timeit
result=a1+a2

44.3 ms ± 535 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[0:2]

array([1, 2])

In [8]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])