In [ ]:
help()


Welcome to Python 3.6's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.6/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> main
No Python documentation found for 'main'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

help> str
Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the give

help> exit
No Python documentation found for 'exit'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

help> exi()
No Python documentation found for 'exi()'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [ ]:
import numpy as np

In [1]:
import requests

In [19]:
url = 'http://www.google.com'

In [20]:
response = requests.get(url).text

In [21]:
response

'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="es-419"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/logos/doodles/2019/celebrating-johann-sebastian-bach-5702425880035328.3-l.png" itemprop="image"><meta content="Celebrando a Johann Sebastian Bach" property="twitter:title"><meta content="¡Compone tus propias canciones inspiradas en Bach con el primer #GoogleDoodle basado en inteligencia artificial! &#127932;#GoogleDoodle" property="twitter:description"><meta content="¡Compone tus propias canciones inspiradas en Bach con el primer #GoogleDoodle basado en inteligencia artificial! &#127932;#GoogleDoodle" property="og:description"><meta content="summary_large_image" property="twitter:card"><meta content="@GoogleDoodles" property="twitter:site"><meta content="https://www.google.com/logos/doodles/2019/celebrating-johann-sebastian-bach-5702425880035328.3-2xa.gif" property="twitter:image"><meta content="https://www.google

In [5]:
import json

In [6]:
my_json = {"A":"1","B":"2"}

In [7]:
type(my_json)

dict

In [14]:
import json
my_json = """{"A":"1","B":"2"}"""
json_object = json.loads(my_json)
value_of_B = json_object["B"]

In [15]:
json_object

{'A': '1', 'B': '2'}

In [16]:
json_object['A']

'1'

In [17]:
import json
a = "1"
json_a = json.dumps(a)

In [18]:
json_a

'"1"'

In [22]:
a=np.array([1,2,3,4])
a

NameError: name 'np' is not defined

In [7]:
import time
import sys

In [9]:
l=range(1000)
print(sys.getsizeof(1)*len(l))

14000


In [14]:
a=np.arange(1000)
print(a.size*a.itemsize)

4000


In [ ]:
size=1000000000
l1=range(size)
l2=range(size)

In [ ]:
a1=np.arange(size)
a2=np.arange(size)

In [19]:
%%timeit
result=[(x+y) for x,y in zip(l1,l2)]

3.04 s ± 262 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
%%timeit
result=a1+a2

44.3 ms ± 535 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[0:2]

array([1, 2])

In [8]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])